### ISSUE TITLE
[Suggestion] Molten Steel

### ISSUE THREAD

**Issue by SynfulChaot** [RCXcrafter/EmbersRekindled#25]
Addition of steel items (molten, seed, recipes for gear and plate, etc...) would be nice for compatibility with mods such as Immersive Engineering and Railcraft.

**Comment by RCXcrafter** [comment]
I don't really see the point in having molten steel since you wouldn't be able to create it with embers machines. If you wanted to make steel plates you would have to create steel ingots with immersive engineering, melt them down and then stamp them into plates. But you can also use immersive engineering machines to turn the ingots directly into plates.
