### ISSUE TITLE
ore blocks such as gold or diamods had their required tool tier changed

### ISSUE THREAD

**Issue by kuba26038** [RCXcrafter/EmbersRekindled#3]
not sure why you would change that, but it appears that ores such as gold and diamonds had their required tool tier changed from iron to diamond. this means that i need a diamond pickaxe to mine diamonds, and i assume this isn't a feature. additionally, when paired with the mod oreganized, an electrum ingot from that mod can be created for way cheaper because of the stamping crafting. when a nugget stamp is used, an ingot of electrum is produced instead of a nugget

**Comment by RCXcrafter** [comment]
I did not change that, I would suggest checking if you aactually can't mine diamon with an iron pickaxe because whatever mod you're using to tell you the mining level might assign a different name to each level than you're used to. If you really can't mine diamond with an iron pickaxe you can check if you have any other mods that might change it because embers doesn't mess with mining levels.
As for the electrum thing, that's a bug in oreganized. It has been fixed already but there hasn't been a new release since the fix so you'll have to wait for a new oreganized release.

**Comment by kuba26038** [comment]
I'm using the jade mod to see the needed tool level, when i install embers diamond ore's needed tool changes to diamond tier and when i uninstall it, it changes back to iron. I'll test if it still happens when i have just those two mods, though.

**Comment by kuba26038** [comment]
here https://www.youtube.com/watch?v=dct2QHsvKqY&feature=youtu.be

**Comment by RCXcrafter** [comment]
Okay I see why this happened now.
